#spring:
#  datasource:
#    password: 1234
#    url: jdbc:h2:mem:db
#    username: sa

    
spring:
#  profiles:
#    active:
#    - mysql
  batch:
    job:
      enabled: false
  datasource:
   # driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/ecommerce?useTimezone=true&serverTimezone=UTC
    username: root
  jpa:
   # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        type: trace
        use_sql_comments: true